version: '3'

vars:
  APPNAME: "jsb01-flasher"
  VERSION: "1.0RC5"
  OUTDIR: "jsb01-firmware"

tasks:
  build:
    desc: Build the flasher executable
    cmds:
      - rsrc -manifest {{.APPNAME}}.manifest -o rsrc.syso
      - go build -ldflags="-s -w -H windowsgui" -o {{.OUTDIR}}/{{.APPNAME}}.exe
      - cp docs/README.txt {{.OUTDIR}}/
      - cp ../Firmware/.pio/build/rpipico/firmware.uf2 {{.OUTDIR}}/
      - 7z a {{.OUTDIR}}-{{.VERSION}}.zip {{.OUTDIR}}/*

