version: '3'

vars:
  VERSION: "1.0RC3"

tasks:
  build:
    desc: Build the flasher executable
    cmds:
      - go build -ldflags="-s -w" -o jsb01-firmware/jsb01-flasher.exe
      - cp docs/README.txt jsb01-firmware/
      - cp ../FIrmware/.pio/build/rpipico/firmware.uf2 jsb01-firmware/
      - 7z a jsb01-firmware-{{.VERSION}}.zip jsb01-firmware/*

